import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'
const isBrowser = typeof window !== 'undefined'
import { Providers } from '@/components/providers';

import { config } from 'telefunc/client'

if (isBrowser) {
  config.telefuncUrl = '/api/_telefunc'
}


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>{children}</Providers>
      </body>
    </html>
  )
}
